config/routes.rb
Rails.application.routes.draw do

  root to: "puzzles#levels"

  get   'login'   => 'sessions#new'
  post  'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'

  resources :users, :puzzles

    post "/puzzles/:id" => "puzzles#win"
    get "/puzzles/levels" => "puzzles#levels"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :puzzle
end

app/models/puzzle.rb
class Puzzle < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  has_and_belongs_to_many :wins

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :puzzles
  has_many :comments
  has_secure_password

  has_and_belongs_to_many  :wins
end

app/models/win.rb
class Win < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :puzzles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionHelper
  include UsersHelper
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController

  #Custom path:
  #Get the main puzzles- these are set apart because they are created by the admin, DZack. DZack can add notes to puzzles, so they are sorted by the notes, which end with the level numebr
  def levels

       @records= User.find_by(user_name:"DZack").puzzles
       @puzzles = []

       @records.each do |puzzle|
         @puzzles.push(puzzle)
       end
       len =@puzzles.length
       found = true
       puts 'start'
       while found
         found = false
        #  puts @puzzles[0].notes
         @puzzles.each_with_index do |puzzle, i|
           break if i == len-1

           puzzle_num = puzzle.notes.split(' ')[1].to_i
           next_puzzle_num = @puzzles[i+1].notes.split(' ')[1].to_i
           if puzzle_num > next_puzzle_num
             found=true
            #  puts 'pre:'
            # puts @puzzles.map{|p| p.notes.split(' ')[1].to_i }
            #  print puzzle_num, ' ', next_puzzle_num
            #  puts ''
            #  puts 'post:'
            # puts @puzzles.class
             @puzzles[i], @puzzles[i+1] = @puzzles[i+1], @puzzles[i]
            #  puts @puzzles.map{|p| p.notes.split(' ')[1].to_i }
            #  puts ''
           end
         end
       end
      # instead of all puzzles, only puzzles by DZack (admin)
      puts 'done'
        puts @puzzles
       @puzzles
  end

  def index
    @puzzles= Puzzle.all
  end

  def show
      @puzzle= Puzzle.find(params[:id])
  end

  def edit
    redirect_to '/login' unless logged_in?
    @puzzle=Puzzle.find(params[:id])
    redirect_to logout_path unless current_user.id == @puzzle.user_id
  end

  def update
    @puzzle= Puzzle.find(params[:id])
    @puzzle.update(puzzle_params)
    @puzzle.user_id=current_user.id
        flash[:notice] = "You've updated this puzzle. Nice."
    redirect_to puzzle_path(@puzzle)


  end

  def new
    redirect_to '/login' unless logged_in?
    @puzzle=Puzzle.new
  end

  def create
    @puzzle= Puzzle.new puzzle_params

    @puzzle.user_id = current_user.id
    #@puzzle.clicks_created= 3
    @puzzle.save
    flash[:notice] = "You made a new puzzle. Good."
    redirect_to puzzle_path(@puzzle)
  end

  # Custom path:
  #find all wins of a given user
  def win
      redirect_to '/login' unless logged_in?
      @puzzle= Puzzle.find(params[:id])
      user_id = current_user.id
      #figure out of the win should count:
      count_win = true
      @wins= Win.all
      @wins.each_with_index do |win|
        #if user has already beaten this puzzle,
        if win.user_id==user_id
          if win.puzzle_id==@puzzle.id
            #don't count it
            count_win=false
            break
          end
        end
      end
      #if it survived the loop, generate new Win object, gives it appropriate puzzle and user id
      if count_win
        @win= Win.new
        @win.user_id=current_user.id
        @win.puzzle_id=@puzzle.id
        #@win.clicks?
        @win.save
        # @puzzle.best_solution < @win.clicks
        #check to see if the clicks it took to win is the best solution; if so, update best solution
        # @puzzle.best_solution=@win.clicks
        @puzzle.best_solver=current_user.user_name
        @puzzle.save
      end

      if @puzzle.user_id ==1 && @puzzle.id != 10
        #NOTE redirect to next puzzle instead?
        next_puzzle = Puzzle.find((params[:id].to_i+1).to_s)
        redirect_to puzzle_path(next_puzzle)
      else
        redirect_to user_path(current_user)
      end

  end

  def destroy
    @puzzle=Puzzle.find(params[:id])
     @win=Win.where(puzzle_id: @puzzle.id)
     unless @win==[]
       @win.each do |win|
         Win.delete(win.id)
       end
     end
    @puzzle.delete
    flash.now[:success] = "You deleted this puzzle. Cool."

    redirect_to puzzles_path
  end

  private
  def puzzle_params
    params.require(:puzzle).permit(:notes, :pattern, :clicks_created)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index

  end

  def new
  end

  def create
    user = User.find_by(user_name: params[:session][:user_name])
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:notice] = "Logged in. Right on."
      redirect_to root_path

    else
      flash.now[:danger] = "Invalid email/password combination. Try again?"
      render 'new'
    end
  end

  def destroy
    log_out
        flash[:notice] = "Logged out. Sweet."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user=User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:alert] = "Account created. Go nuts."
      log_in @user
      redirect_to root_path
    else
      render new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
    @wins=Win.all

  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation, :profile_pic)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/puzzle_helper.rb
module PuzzleHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user = @current_user || User.find_by(id: session[:user_id])
    # if @current_user.nil?
    # @current_user = User.find_by(id: session[:user_id])
    # else
    #   @current_user
    # end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def find_winning_puzzles
  


  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>

  <title>Cubonic</title>
  <div class="container-fluid header-bar">
    <div class="row">
      <div class="col-md-1 col-md-offset-1 logo_container">
        <div id='logo_container'>
          <%= link_to root_path do %>
            <div class='show-front' type='logo'>
              <figure class="front"></figure>
              <figure class="back"></figure>
              <figure class="right"></figure>
              <figure class="left"></figure>
              <figure class="top"></figure>
              <figure class="bottom"></figure>
            </div>
            <% end %>
        </div>
      </div>
      <div class="col-md-2" id='title'>
        <!-- <br>
        <br> -->
        <h1> Cubonic</h1>
      </div>
      <!-- <div class='col-sm-5'>



      </div>
      <div class='col-sm-2'>
      </div> -->
    </div>
  </div>
  </div>

  <nav class="navbar nav-tabs navigation-bar">
    <div class="container-fluid">

      <% if logged_in? %>
        <div class="btn navbar-btn" type="div">
          <%= link_to "Home", root_path %>
        </div>
        <div class="btn navbar-btn" type="div">
          <%= link_to "User Generated Puzzles", puzzles_path %>
        </div>
        <div class="btn navbar-btn" type="div">
          <%= link_to "Create A New Puzzle", new_puzzle_path %>
        </div>
        <div class="btn navbar-btn" type="div">
          <%= link_to current_user.user_name, user_path(current_user) %>

        </div>
        <div class="btn navbar-btn" type="div">
          <%=link_to "Log Out", logout_path %>
        </div>

        <% else %>
          <div class="btn navbar-btn" type="div">
              <%= link_to "Home", root_path %>

          </div>
          <div class="btn navbar-btn" type="div">
            <%= link_to "User Generated Puzzles", puzzles_path %>
          </div>
          <div class="btn navbar-btn" type="div">
          <%=link_to "Log In", login_path %>
          </div>
          <div class="btn navbar-btn" type="div">
            <%=link_to "Sign Up", new_user_path %>
          </div>

          <% end %>
    </div>
  </nav>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

</head>

<body>

  <%= yield %>

  <div id='alert'>
  If you are reading this, your window is either too small (in which case, make it bigger) or you're on a mobile device (in which case, go get a computer).
  <div>

</body>
</body>

</html>

app/views/puzzles/_bar.html.erb
<nav class="navbar navbar-right navigation-bar">
  <% if logged_in? %>
  <div class="btn navbar-btn" type="div"> <%= link_to "User Generated Puzzles", puzzles_path %></div>
  <div class="btn navbar-btn" type="div"><%= link_to "Home", root_path %></div>
  <div class="btn navbar-btn" type="div"><%=link_to "Log Out", logout_path %></div>
  <div class="btn navbar-btn" type="div">  <%= link_to current_user.user_name, user_path(current_user) %></div>

  <% else %>
  <div class="btn navbar-btn" type="div">  <%=link_to "Log In", login_path %></div>
  <div class="btn navbar-btn" type="div"> <%= link_to "User Generated Puzzles", puzzles_path %></div>
  <div class="btn navbar-btn" type="div"><%= link_to "Home", root_path %></div>
  <div class="btn navbar-btn" type="div">      <%=link_to "Sign Up", new_user_path %></div>
  <% end %>
</nav>

app/views/puzzles/_buttons.html.erb
<div id="buttons">
  <div id="reset" class="button">Reset </div>
</div>

app/views/puzzles/_levelgrid.html.erb
    <div class="row" id="row1">
      <div class="level-box" row="1" col="1"></div>
      <div class="level-box" row="1" col="2"></div>
      <div class="level-box" row="1" col="3"></div>
      <div class="level-box" row="1" col="4"></div>
      <div class="level-box" row="1" col="5"></div>
      <div class="level-box" row="1" col="6"></div>
      <div class="level-box" row="1" col="7"></div>
      <div class="level-box" row="1" col="8"></div>
      <div class="level-box" row="1" col="9"></div>
    </div>
    <div class="row" id="row2">
      <div class="level-box" row="2" col="1"></div>
      <div class="level-box" row="2" col="2"></div>
      <div class="level-box" row="2" col="3"></div>
      <div class="level-box" row="2" col="4"></div>
      <div class="level-box" row="2" col="5"></div>
      <div class="level-box" row="2" col="6"></div>
      <div class="level-box" row="2" col="7"></div>
      <div class="level-box" row="2" col="8"></div>
      <div class="level-box" row="2" col="9"></div>
    </div>
    <div class="row" id="row3">
      <div class="level-box" row="3" col="1"></div>
      <div class="level-box" row="3" col="2"></div>
      <div class="level-box" row="3" col="3"></div>
      <div class="level-box" row="3" col="4"></div>
      <div class="level-box" row="3" col="5"></div>
      <div class="level-box" row="3" col="6"></div>
      <div class="level-box" row="3" col="7"></div>
      <div class="level-box" row="3" col="8"></div>
      <div class="level-box" row="3" col="9"></div>
    </div>
    <div class="row" id="row4">
      <div class="level-box" row="4" col="1"></div>
      <div class="level-box" row="4" col="2"></div>
      <div class="level-box" row="4" col="3"></div>
      <div class="level-box" row="4" col="4"></div>
      <div class="level-box" row="4" col="5"></div>
      <div class="level-box" row="4" col="6"></div>
      <div class="level-box" row="4" col="7"></div>
      <div class="level-box" row="4" col="8"></div>
      <div class="level-box" row="4" col="9"></div>
    </div>
    <div class="row" id="row5">
      <div class="level-box" row="5" col="1"></div>
      <div class="level-box" row="5" col="2"></div>
      <div class="level-box" row="5" col="3"></div>
      <div class="level-box" row="5" col="4"></div>
      <div class="level-box" row="5" col="5"></div>
      <div class="level-box" row="5" col="6"></div>
      <div class="level-box" row="5" col="7"></div>
      <div class="level-box" row="5" col="8"></div>
      <div class="level-box" row="5" col="9"></div>
    </div>
    <div class="row" id="row6">
      <div class="level-box" row="6" col="1"></div>
      <div class="level-box" row="6" col="2"></div>
      <div class="level-box" row="6" col="3"></div>
      <div class="level-box" row="6" col="4"></div>
      <div class="level-box" row="6" col="5"></div>
      <div class="level-box" row="6" col="6"></div>
      <div class="level-box" row="6" col="7"></div>
      <div class="level-box" row="6" col="8"></div>
      <div class="level-box" row="6" col="9"></div>
    </div>
    <div class="row" id="row7">
      <div class="level-box" row="7" col="1"></div>
      <div class="level-box" row="7" col="2"></div>
      <div class="level-box" row="7" col="3"></div>
      <div class="level-box" row="7" col="4"></div>
      <div class="level-box" row="7" col="5"></div>
      <div class="level-box" row="7" col="6"></div>
      <div class="level-box" row="7" col="7"></div>
      <div class="level-box" row="7" col="8"></div>
      <div class="level-box" row="7" col="9"></div>
    </div>
    <div class="row" id="row8">
      <div class="level-box" row="8" col="1"></div>
      <div class="level-box" row="8" col="2"></div>
      <div class="level-box" row="8" col="3"></div>
      <div class="level-box" row="8" col="4"></div>
      <div class="level-box" row="8" col="5"></div>
      <div class="level-box" row="8" col="6"></div>
      <div class="level-box" row="8" col="7"></div>
      <div class="level-box" row="8" col="8"></div>
      <div class="level-box" row="8" col="9"></div>
    </div>
    <div class="row" id="row9">
      <div class="level-box" row="9" col="1"></div>
      <div class="level-box" row="9" col="2"></div>
      <div class="level-box" row="9" col="3"></div>
      <div class="level-box" row="9" col="4"></div>
      <div class="level-box" row="9" col="5"></div>
      <div class="level-box" row="9" col="6"></div>
      <div class="level-box" row="9" col="7"></div>
      <div class="level-box" row="9" col="8"></div>
      <div class="level-box" row="9" col="9"></div>
    </div>
  </div>






<!-- jquery only works wth this in the body??? -->

app/views/puzzles/_minigrid.html.erb
    <div class="row" id="row1">
      <div class="mini_box" row="1" col="1"></div>
      <div class="mini_box" row="1" col="2"></div>
      <div class="mini_box" row="1" col="3"></div>
      <div class="mini_box" row="1" col="4"></div>
      <div class="mini_box" row="1" col="5"></div>
      <div class="mini_box" row="1" col="6"></div>
      <div class="mini_box" row="1" col="7"></div>
      <div class="mini_box" row="1" col="8"></div>
      <div class="mini_box" row="1" col="9"></div>
    </div>
    <div class="row" id="row2">
      <div class="mini_box" row="2" col="1"></div>
      <div class="mini_box" row="2" col="2"></div>
      <div class="mini_box" row="2" col="3"></div>
      <div class="mini_box" row="2" col="4"></div>
      <div class="mini_box" row="2" col="5"></div>
      <div class="mini_box" row="2" col="6"></div>
      <div class="mini_box" row="2" col="7"></div>
      <div class="mini_box" row="2" col="8"></div>
      <div class="mini_box" row="2" col="9"></div>
    </div>
    <div class="row" id="row3">
      <div class="mini_box" row="3" col="1"></div>
      <div class="mini_box" row="3" col="2"></div>
      <div class="mini_box" row="3" col="3"></div>
      <div class="mini_box" row="3" col="4"></div>
      <div class="mini_box" row="3" col="5"></div>
      <div class="mini_box" row="3" col="6"></div>
      <div class="mini_box" row="3" col="7"></div>
      <div class="mini_box" row="3" col="8"></div>
      <div class="mini_box" row="3" col="9"></div>
    </div>
    <div class="row" id="row4">
      <div class="mini_box" row="4" col="1"></div>
      <div class="mini_box" row="4" col="2"></div>
      <div class="mini_box" row="4" col="3"></div>
      <div class="mini_box" row="4" col="4"></div>
      <div class="mini_box" row="4" col="5"></div>
      <div class="mini_box" row="4" col="6"></div>
      <div class="mini_box" row="4" col="7"></div>
      <div class="mini_box" row="4" col="8"></div>
      <div class="mini_box" row="4" col="9"></div>
    </div>
    <div class="row" id="row5">
      <div class="mini_box" row="5" col="1"></div>
      <div class="mini_box" row="5" col="2"></div>
      <div class="mini_box" row="5" col="3"></div>
      <div class="mini_box" row="5" col="4"></div>
      <div class="mini_box" row="5" col="5"></div>
      <div class="mini_box" row="5" col="6"></div>
      <div class="mini_box" row="5" col="7"></div>
      <div class="mini_box" row="5" col="8"></div>
      <div class="mini_box" row="5" col="9"></div>
    </div>
    <div class="row" id="row6">
      <div class="mini_box" row="6" col="1"></div>
      <div class="mini_box" row="6" col="2"></div>
      <div class="mini_box" row="6" col="3"></div>
      <div class="mini_box" row="6" col="4"></div>
      <div class="mini_box" row="6" col="5"></div>
      <div class="mini_box" row="6" col="6"></div>
      <div class="mini_box" row="6" col="7"></div>
      <div class="mini_box" row="6" col="8"></div>
      <div class="mini_box" row="6" col="9"></div>
    </div>
    <div class="row" id="row7">
      <div class="mini_box" row="7" col="1"></div>
      <div class="mini_box" row="7" col="2"></div>
      <div class="mini_box" row="7" col="3"></div>
      <div class="mini_box" row="7" col="4"></div>
      <div class="mini_box" row="7" col="5"></div>
      <div class="mini_box" row="7" col="6"></div>
      <div class="mini_box" row="7" col="7"></div>
      <div class="mini_box" row="7" col="8"></div>
      <div class="mini_box" row="7" col="9"></div>
    </div>
    <div class="row" id="row8">
      <div class="mini_box" row="8" col="1"></div>
      <div class="mini_box" row="8" col="2"></div>
      <div class="mini_box" row="8" col="3"></div>
      <div class="mini_box" row="8" col="4"></div>
      <div class="mini_box" row="8" col="5"></div>
      <div class="mini_box" row="8" col="6"></div>
      <div class="mini_box" row="8" col="7"></div>
      <div class="mini_box" row="8" col="8"></div>
      <div class="mini_box" row="8" col="9"></div>
    </div>
    <div class="row" id="row9">
      <div class="mini_box" row="9" col="1"></div>
      <div class="mini_box" row="9" col="2"></div>
      <div class="mini_box" row="9" col="3"></div>
      <div class="mini_box" row="9" col="4"></div>
      <div class="mini_box" row="9" col="5"></div>
      <div class="mini_box" row="9" col="6"></div>
      <div class="mini_box" row="9" col="7"></div>
      <div class="mini_box" row="9" col="8"></div>
      <div class="mini_box" row="9" col="9"></div>
    </div>
  </div>






<!-- jquery only works wth this in the body??? -->

app/views/puzzles/edit.html.erb
<h1 id='new-headline'>Edit Your puzzle</h1>

<div id="pattern"><%=@puzzle.pattern %></div>

<%= form_for(@puzzle) do |f| %>
<ul>
  <% @puzzle.errors.full_messages.each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<p>
  <%= f.text_area :pattern %>
</p>
<p>
  <%= f.text_area :clicks_created %>
</p>
<p class="submit_button" id='create-puzzle'>
  <%= f.submit %>
</p>
<% end %>

<div>
  <div , class="board" id="edit_board">
    <%= render partial: 'grid' %>
  </div>
  <div id="reset-new"  class="button reset">Reset </div>
</div>

app/views/puzzles/index.html.erb
<% flash.each do |message_type, message| %>
<div class="alert alert-<%= message_type %>">
  <h1><%= message %></h1>
</div>
<% end %>

<br>
<br>
<div class="container">
  <div class="row user-puzzles-header">
    <h1 class="col-md-6">User-Created Puzzles</h1>
  </div>
  <div class="row">
    <div class="col-md-6 directions-users">
      Play puzzles created by users (like you!) or create your own.   </div >
  </div>
</div>

<ul class="container">
    <% @puzzles.reverse.each_with_index do |puzzle, index| %>
    <% unless puzzle.user_id==1 %>
    <div class="col-md-3">
      <div class='index-mini-li'>
        <%= link_to puzzle_path(puzzle) do %>
        <div class="board mini_board" id="mini_board<%=index%>">
          <%= render partial: 'minigrid' %>
        </div>
        <% end %>
        <div class="hidden" id="mini_encrypt<%=index%>"><%= puzzle.pattern%></div>
                <div class="user-puzzle-options">
                  <%= link_to puzzle.user.user_name, user_path(puzzle.user) %>,
                  <%= puzzle.clicks_created %> clicks
                  <% unless current_user==nil %>
                  <%if current_user.is_admin %>
                  <%= link_to "Delete", puzzle_path(puzzle), method: :delete %>

                  <br>
                  <% end %>
                  <%end%>
                </div>

        <script>
          // = require jquery
          var index = <%=index%>;
          var encryptedGrid = $('#mini_encrypt' + index).text();
          var board = $('#mini_board' + index).children()
            .children()
          decryptMini(encryptedGrid, board)
        </script>

      </div>
    </div> <!-- col -->
      <% end %>
    <% end %>
  <!-- </div><!-- row -->
</ul> <!-- contailer -->

app/views/puzzles/levels.html.erb
<% flash.each do |message_type, message| %>
<div class="alert alert-<%= message_type %>">
  <h1><%= message %></h1>
</div>
<% end %>


<div class="container">
  <div class="row user-puzzles-header">
    <h1 class="col-md-6">Single Player</h1>
  </div>
  <div class="row">
    <div class="col-md-6 directions-main">
      Welcome to Cubonic. Click a puzzle to play it, or create your own and try other user puzzles. Good luck.
    </div >
  </div>
</div>

<ul class="container">
    <% @puzzles.each_with_index do |puzzle, index| %>
    <%# render a mini board with unique id %>
    <div class="col-md-6">
      <div class='level-mini-li'>
        <div class="level-label">
          <%= puzzle.notes %>
        </div>
        <%= link_to puzzle_path(puzzle) do %>
        <div class="board level_board" id="level_board<%=index%>">
          <%= render partial: 'levelgrid' %>
        </div>
        <%end %>
        <%# fetch encrypted string to feed to encrypt function %>
        <div class="hidden" id="level_encrypt<%=index%>"><%= puzzle.pattern%></div>

        <%# decrypt, put onto each level board %>
        <script>
          // = require jquery
          var index = <%=index%>;
          var encryptedGrid = $('#level_encrypt' + index).text();
          var board = $('#level_board' + index).children()
            .children()
          decryptMini(encryptedGrid, board)
        </script>

      </div>
    </div>

    <% end %>
  <!-- </div> -->
</ul>

app/views/users/_bar.html.erb
<div id="status_bar">
<% if logged_in? %>
  <p> Hi <%= link_to current_user.user_name, user_path(current_user) %> <%= link_to "User Generated Puzzles", puzzles_path %> <%= link_to "Home", root_path %>  <%=link_to "Log Out", logout_path %></p>
  <% if current_user.is_admin %>
    <p><%= "Admin" %>  </p>
  <% end %>
  <%else%>
      <p><%= link_to "User Generated Puzzles", puzzles_path %> <%= link_to "Home", root_path %>  <%=link_to "Log In", login_path %> <%=link_to "Sign Up", new_user_path %></p>

<% end %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<!-- <div class="container">
  <div class="row">
    <h1 class='col-md-4'><%= @user.user_name%>'s Page</h1>
  </div>
</div> -->


<br>
<div class="container">
  <div class="row">
    <h2 class='col-md-4'><%= @user.user_name%>'s Puzzles:</h2>
  </div>
</div>

<ul class="container">

  <% @user.puzzles.each_with_index do |puzzle, index| %>
  <div class="col-md-3">

    <div class="user-mini-li">
      <%= link_to puzzle_path(puzzle) do %>
      <div class="board mini_board" id="mini-board<%=index%>">
        <%# this next line is the only diffrence between index page %>
        <%= render partial: './puzzles/minigrid' %>
      </div>
      <% end %>
      <%# fetch encrypted string to feed to encrypt function %>
      <div class="hidden" id="mini_encrypt<%=index%>"><%= puzzle.pattern%></div>

      <div class="profile-options">


      <% unless current_user==nil %>
      <%if current_user==@user || current_user.is_admin %>
      <%= link_to "Delete", puzzle_path(puzzle), method: :delete %>
             <%= link_to "Edit", edit_puzzle_path(puzzle) %>
      <% end %>
      <%end%>
        </div>

      <%# decrypt, put onto each mini board %>
      <script>
        // = require jquery
        var index = <%=index%>;
        var encryptedGrid = $('#mini_encrypt' + index).text();
        var board = $('#mini-board' + index).children()
          .children()
        decryptMini(encryptedGrid, board)
      </script>




    </div>
  </div>
  <% end %>

</ul>
<!-- container -->

<br>
<br>
<div class="container">
  <div class="row">

    <h2>Puzzles <%= @user.user_name%> has solved:</h2>
  </div>
</div>



<ul class='container'>

  <% @wins.each_with_index do |win, index| %>
  <div class="col-md-3">

    <% if win.user_id == @user.id %>
    <% @puzzle=Puzzle.find(win.puzzle_id) %>

    <!-- <%= link_to puzzle_path(@puzzle) do %> -->
    <div class="user-mini-li">
      <%= link_to puzzle_path(@puzzle) do %>
      <div class="board mini_board" id="mini-board<%=index+1000%>">
        <%= render partial: './puzzles/minigrid' %>
        <div class="profile-options">


        <%= link_to @puzzle.user.user_name, user_path(@puzzle.user) %>
        </div>
      </div>
      <% end %>

    </div>
    <% end %>

    <div class="hidden" id="mini_encrypt<%=index+1000%>"><%= @puzzle.pattern%></div>
    <%# decrypt, put onto each mini board %>
    <script>
      // = require jquery
      var index = <%=index%>;
      var encryptedGrid = $('#mini_encrypt' + (index + 1000)).text();
      var board = $('#mini-board' + (index + 1000)).children()
        .children()
      decryptMini(encryptedGrid, board)
    </script>
    <% end %>
    <!-- ? -->

  </div>
  <!-- end col -->
  <% end %>
  <!-- end loop -->
</ul>
<!-- end container -->